Elasticsearch.WEB/Models/Blog.cs
using System.Text.Json.Serialization;

namespace Elasticsearch.WEB.Models
{
    public class Blog
    {
        [JsonPropertyName("_id")]
        public string Id { get; set; } = null!;
        [JsonPropertyName("title")]
        public string Title { get; set; } = null!;
        [JsonPropertyName("content")]
        public string Content { get; set; } = null!;
        [JsonPropertyName("tags")]
        public string[] Tags { get; set; } = null!;
        [JsonPropertyName("user_id")]
        public Guid UserId { get; set; }
        [JsonPropertyName("created")]
        public DateTime Created { get; set; }
    }
}

Elasticsearch.WEB/Models/ECommerce.cs
using System.Text.Json.Serialization;

namespace ElasticSearch.WEB.Models
{
    public class ECommerce
    {
        [JsonPropertyName("_id")]
        public string Id { get; set; } = null!;

        [JsonPropertyName("customer_first_name")]
        public string CustomerFirstName { get; set; } = null!;

        [JsonPropertyName("customer_last_name")]
        public string CustomerLastName { get; set; } = null!;
           [JsonPropertyName("customer_gender")]
        public string Gender { get; set; } = null!;

        [JsonPropertyName("customer_full_name")]
        public string CustomerFullName { get; set; } = null!;

        [JsonPropertyName("category")]
        public string[] Category { get; set; } = null!;
        [JsonPropertyName("taxful_total_price")]
        public double TaxfulTotalPrice { get; set; }

        [JsonPropertyName("order_id")]
        public int OrderId { get; set; }
        [JsonPropertyName("order_date")]
        public DateTime OrderDate { get; set; }

        [JsonPropertyName("products")]
        public Product[] Products { get; set; }
    }
    public class Product
    {
        [JsonPropertyName("product_id")]
        public long ProductId { get; set; }
        [JsonPropertyName("product_name")]
        public string ProductName { get; set; }
    }
}

Elasticsearch.WEB/Models/ErrorViewModel.cs
namespace Elasticsearch.WEB.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Elasticsearch.WEB/Controllers/BlogController.cs
using Elasticsearch.WEB.Services;
using Elasticsearch.WEB.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace Elasticsearch.WEB.Controllers
{
    public class BlogController : Controller
    {
        private BlogService blogService;

        public BlogController(BlogService blogService)
        {
            this.blogService = blogService;
        }

        public IActionResult Save()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Save(BlogCreateViewModel model)
        {
           var isSucces= await this.blogService.SaveAsync(model);
            if (!isSucces)
            {
                TempData["result"] = "Kayıt başarısız";
                return RedirectToAction(nameof(BlogController.Save));
            }
            TempData["result"] = "Kayıt başarılı";
            return RedirectToAction(nameof(BlogController.Save));
        }
        public async Task<IActionResult> Search(string searchText)
        {
            var data = await this.blogService.SearchAsync(searchText);
            return View(data);
        }
    }
}

Elasticsearch.WEB/Controllers/ECommerceController.cs
using Elasticsearch.WEB.Services;
using Elasticsearch.WEB.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace Elasticsearch.WEB.Controllers
{
    public class ECommerceController : Controller
    {
		private readonly ECommerceService _service;

		public ECommerceController(ECommerceService service)
		{
			_service = service;
		}

		public async Task<IActionResult> Search([FromQuery] SearchPageViewModel searchPageView)
		{

			var (eCommerceList, totalCount, pageLinkCount) = await _service.SearchAsync(searchPageView.SearchViewModel, searchPageView.Page,
				searchPageView.PageSize);


			searchPageView.List = eCommerceList;
			searchPageView.TotalCount = totalCount;
			searchPageView.PageLinkCount = pageLinkCount;




			return View(searchPageView);
		}
	}
}

Elasticsearch.WEB/Controllers/HomeController.cs
using Elasticsearch.WEB.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Elasticsearch.WEB.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Elasticsearch.WEB/Views/Blog/Save.cshtml
@using Elasticsearch.WEB.ViewModel
@model BlogCreateViewModel
@{
    ViewData["Title"] = "Save";
}

<div class="row">

    <div class="col-md-6 offset-md-3">

        @if (TempData["result"] != null)
        {
            <div class="alert alert-info">
                @TempData["result"]
            </div>
        }
        <h2>Blog Create</h2>

        <form asp-action="Save">


            <div class="mb-3">
                <label asp-for="Title" class="form-label"></label>
                <input asp-for="Title" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="Content" class="form-label"></label>
                <textarea asp-for="Content" class="form-control" rows="3"></textarea>
            </div>
            <div class="mb-3">
                <label asp-for="Tags" class="form-label"></label>
                <input asp-for="Tags" class="form-control">
            </div>


            <div class="mb-3">
                <button class="btn btn-primary" type="submit">Save</button>
            </div>





        </form>



    </div>


</div>

Elasticsearch.WEB/Views/Blog/Search.cshtml
@model List<Elasticsearch.WEB.ViewModel.BlogViewModel>
@{
    ViewData["Title"] = "SearchAsync";

}

<div class="container">
    <div class="col-md-10 offset-md-1">

        <form asp-action="Search">
            <div class="mb-3">


                <label>SearchAsync(Title,Content)</label>
                <input value="@ViewBag.searchText" name="searchText" class="form-control" />
            </div>

            <button type="submit">Search</button>
        </form>


        @if (!Model.Any())
        {
            <div class="alert alert-info">
                sonuç bulunamamıştır.
            </div>
        }

        else
        {

            <table class="table">

                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Title</th>
                        <th>Content</th>
                        <th>UserId</th>
                        <th>Tags</th>
                        <th>Created</th>
                    </tr>



                </thead>
                <tbody>
                    @foreach (var blog in Model)
                    {
                        <tr>

                            <td>@blog.Id</td>
                            <td>@blog.Title</td>
                            <td>@blog.Content</td>
                            <td>@blog.UserId</td>
                            <td>@blog.Tags</td>
                            <td>@blog.Created</td>
                        </tr>




                    }
                </tbody>
            </table>
        }

    </div>



</div>

Elasticsearch.WEB/Views/ECommerce/Search.cshtml
@using Elasticsearch.WEB.ViewModel
﻿@{
	ViewData["Title"] = "Search";
}
@model SearchPageViewModel
<div class="container">
	<div class="row">
		<div class="col-md-3">
			<form asp-action="Search" method="Get">

				<div class="mb-3">
					<label asp-for="SearchViewModel.CustomerFullName" class="form-label"></label>
					<input asp-for="SearchViewModel.CustomerFullName" class="form-control">
				</div>
				<div class="mb-3">
					<label asp-for="SearchViewModel.Category" class="form-label"></label>
					<input asp-for="SearchViewModel.Category" class="form-control">
				</div>
				<div class="mb-3">
					<label asp-for="SearchViewModel.Gender" class="form-label"></label>
					<input asp-for="SearchViewModel.Gender" class="form-control" rows="3"></input>
				</div>
				<div class="mb-3">
					<label asp-for="SearchViewModel.OrderDateStart" class="form-label"></label>
					<input asp-for="SearchViewModel.OrderDateStart" class="form-control">
				</div>
				<div class="mb-3">
					<label asp-for="SearchViewModel.OrderDateEnd" class="form-label"></label>
					<input asp-for="SearchViewModel.OrderDateEnd" class="form-control">
				</div>

				<div class="mb-3">
					<button class="btn btn-primary" type="submit">Search</button>
				</div>









			</form>




		</div>
		<div class="col-md-9">

			<div class="alert alert-success">
				<span> Toplam @Model.TotalCount kayıt bulunmuştur</span>
			</div>

			<table class="table table-striped">

				<thead>
					<tr>
						<th>Customer Full Name</th>
						<th>Order Date</th>
						<th>Gender</th>
						<th>TaxfulTotalPrice</th>
						<th>Category</th>
						<th>OrderId</th>
					</tr>
				</thead>
				<tbody>

					@foreach (var item in Model.List)
					{

						<tr>
							<td>@item.CustomerFullName</td>
							<td>@item.OrderDate</td>
							<td>@item.Gender</td>
							<td>@item.TaxfulTotalPrice</td>
							<td>@item.Category</td>
							<td>@item.OrderId</td>
						</tr>




					}

				</tbody>
			</table>

			<nav>
				<ul class="pagination">

					<li class="page-item">
						<a class="page-link" href="@Model.CreatePageUrl(Context.Request,1,Model.PageSize)">First</a>
					</li>


					@for (int i = Model.StartPage(); i <= @Model.EndPage(); i++)
					{
						<li class="page-item @(Model.Page==i ?"active" :"")">
							<a class="page-link" href="@Model.CreatePageUrl(Context.Request,i,Model.PageSize)">@i</a>
						</li>
					}

					<li class="page-item">
						<a class="page-link" href="@Model.CreatePageUrl(Context.Request,Model.PageLinkCount,Model.PageSize)">Last</a>
					</li>

				</ul>



			</nav>

		</div>
	</div>

</div>

Elasticsearch.WEB/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Elasticsearch.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Elasticsearch.WEB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Elasticsearch.WEB.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Elasticsearch.WEB</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Blog" asp-action="Save">Blog Save</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Blog" asp-action="Search">Blog Search</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Elasticsearch.WEB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>